version: '3'

services:
  postgres:
    restart: always
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - .data/:/tmp
    env_file:
      - .env

  python:
    restart: on-failure
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src

    